//burger-ingredient
export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" =
    "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" =
    "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" =
    "GET_INGREDIENTS_FAILED";
export const INCREASE_INGREDIENT_COUNTER: "INCREASE_INGREDIENT_COUNTER" =
    "INCREASE_INGREDIENT_COUNTER";
export const DECREASE_INGREDIENT_COUNTER: "DECREASE_INGREDIENT_COUNTER" =
    "DECREASE_INGREDIENT_COUNTER";
