//burger-constructor
export const SWAP_CONSTRUCTOR_INGREDIENTS: "SWAP_CONSTRUCTOR_INGREDIENTS" =
    "SWAP_CONSTRUCTOR_INGREDIENTS";
export const ADD_CONSTRUCTOR_INGREDIENT: "ADD_CONSTRUCTOR_INGREDIENT" =
    "ADD_CONSTRUCTOR_INGREDIENT";
export const DELETE_CONSTRUCTOR_INGREDIENT: "DELETE_CONSTRUCTOR_INGREDIENT" =
    "DELETE_CONSTRUCTOR_INGREDIENT";
export const UPDATE_CONSTRUCTOR_BUN: "UPDATE_CONSTRUCTOR_BUN" =
    "UPDATE_CONSTRUCTOR_BUN";