export const GET_FEED_REQUEST: "GET_FEED_REQUEST" = "GET_FEED_REQUEST";
export const GET_FEED_SUCCESS: "GET_FEED_SUCCESS" = "GET_FEED_SUCCESS";
export const GET_FEED_FAILED: "GET_FEED_FAILED" = "GET_FEED_FAILED";
