export const ORDERS_WS_CONNECTION_START: "ORDERS_WS_CONNECTION_START" =
    "ORDERS_WS_CONNECTION_START";
export const ORDERS_WS_CONNECTION_SUCCESS: "ORDERS_WS_CONNECTION_SUCCESS" =
    "ORDERS_WS_CONNECTION_SUCCESS";
export const ORDERS_WS_CONNECTION_ERROR: "ORDERS_WS_CONNECTION_ERROR" =
    "ORDERS_WS_CONNECTION_ERROR";
export const ORDERS_WS_CONNECTION_CLOSED: "ORDERS_WS_CONNECTION_CLOSED" =
    "ORDERS_WS_CONNECTION_CLOSED";
export const ORDERS_WS_GET_MESSAGE: "ORDERS_WS_GET_MESSAGE" =
    "ORDERS_WS_GET_MESSAGE";
export const ORDERS_WS_SEND_MESSAGE: "ORDERS_WS_SEND_MESSAGE" =
    "ORDERS_WS_SEND_MESSAGE";
