// auth
export const AUTH_REQUEST: "AUTH_REQUEST" = "AUTH_REQUEST";
export const AUTH_SUCCESS: "AUTH_SUCCESS" = "AUTH_SUCCESS";
export const AUTH_FAILED: "AUTH_FAILED" = "AUTH_FAILED";

//register
export const REGISTER_REQUEST: "REGISTER_REQUEST" = "REGISTER_REQUEST";
export const REGISTER_SUCCESS: "REGISTER_SUCCESS" = "REGISTER_SUCCESS";
export const REGISTER_FAILED: "REGISTER_FAILED" = "REGISTER_FAILED";

//logout
export const LOGOUT_REQUEST: "LOGOUT_REQUEST" = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS: "LOGOUT_SUCCESS" = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED: "LOGOUT_FAILED" = "LOGOUT_FAILED";

//update token
export const UPDATE_TOKEN_REQUEST: "UPDATE_TOKEN_REQUEST" =
    "UPDATE_TOKEN_REQUEST";
export const UPDATE_TOKEN_SUCCESS: "UPDATE_TOKEN_SUCCESS" =
    "UPDATE_TOKEN_SUCCESS";
export const UPDATE_TOKEN_FAILED: "UPDATE_TOKEN_FAILED" = "UPDATE_TOKEN_FAILED";

//update user info
export const UPDATE_USER_INFO_REQUEST: "UPDATE_USER_INFO_REQUEST" =
    "UPDATE_USER_INFO_REQUEST";
export const UPDATE_USER_INFO_SUCCESS: "UPDATE_USER_INFO_SUCCESS" =
    "UPDATE_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_FAILED: "UPDATE_USER_INFO_FAILED" =
    "UPDATE_USER_INFO_FAILED";

//get user
export const GET_USER_REQUEST: "GET_USER_REQUEST" = "GET_USER_REQUEST";
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const GET_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";

export const SET_AUTHED: "SET_AUTHED" = "SET_AUTHED";

export const SET_IS_CODE_SENT: "SET_IS_CODE_SENT" = "SET_IS_CODE_SENT";
